version: "3.9"

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USE_POWERLEVEL10K: ${USE_POWERLEVEL10K:-false}
    container_name: devcontainer
    volumes:
      - ..:/python-template:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
